image: archlinux/base

before_script:
  - pacman -Syu --noconfirm vala meson libgee gobject-introspection libsoup

stages:
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: normal

build:
  stage: build
  script:
    - meson setup --buildtype release --prefix /usr -Dwith-docs=false build .
    - ninja -C build
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - ninja -C build test
