sudo: false

os:
  - linux

language:
  - c

services:
  - docker

before_install:
  - docker pull archlinux/base
  - docker build -t utlib .

script:
  - docker run utlib /bin/sh -c "cd /root; TRAVIS=true CC=$CC meson build -Dwithdocs=false; ninja -C build"
