sudo: false
language: c
dist: trusty

services:
  - docker

before_install:
  - docker pull archlinux/base
  - docker run archlinux/base /bin/sh -c "pacman -Syu --noconfirm vala meson libgee"

script:
 - docker run -v $PWD:/build archlinux/base /bin/sh -c "cd /build; meson builddir; ninja -C build"
