sudo: false

os:
  - linux

language:
  - c

services:
  - docker

before_install:
  - docker pull archlinux/base

script:
  - docker build -t utlib .
  - docker run utlib /bin/sh -c "cd /root; TRAVIS=true CC=$CC meson build; ninja -C build"
