on:
  push:
    paths:
    - .github/workflows/*
    - lib/**
    - tests/**
name: Continuous Integration
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Install dependencies
      run: |
        dnf install -y vala libgee-devel libarchive-devel gobject-introspection-devel \
            gobject-introspection meson ninja-build glib2-devel libsoup-devel git
    - name: Build & install vul
      run: |
        git clone https://gitlab.gnome.org/BZHDeveloper/vul.git
        meson vul build-vul --prefix /usr --buildtype release
        ninja -C build-vul
        sudo ninja -C build-vul install
    - name: Build UTLib
      run: |
        meson build --prefix /usr
        ninja -C build
    - name: Upload vul build files
      uses: actions/upload-artifact@v2
      with:
        name: build-vul
        path: build-vul
    - name: Upload UTLib build files
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
  test:
    name: Test
    runs-on: ubuntu-latest
    container: fedora:latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
    - name: Install dependencies
      run: dnf install -y meson ninja-build libgee libarchive glib2 libsoup git
    - name: Reinstall vul
      run: sudo meson install -C build-vul --no-rebuild
    - name: Test UTLib
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: meson test -C build --no-rebuild
